title: Default

tabs:
  content:
    label: Content
    icon: page
    columns:
      - width: 2/3
        sticky: true
        sections:
          livePreview:
            type: preview

      - width: 1/3
        fields:
          blocks:
            label: Content
            type: blocks
            extends:
              - fieldsets/content

  seo: seo/page

  files: tabs/files

  pageInfo: tabs/page-info
